-- Query Name: qryEXPIRATIONS09
-- Extracted: 2026-02-04 13:04:22

SELECT IIf(IsNull([tblPeopleClientsResidentialServices]![CityTown]),"",[tblPeopleClientsResidentialServices]![CityTown] & " - " & [tblPeopleClientsResidentialServices]![Location]) AS LocRes, IIf(IsNull([tblPeopleClientsCLOServices]![CityTown]),"",[tblPeopleClientsCLOServices]![CityTown] & " - " & [tblPeopleClientsCLOServices]![Location]) AS LocCLO, IIf(IsNull([tblPeopleClientsDayServices]![CityTown]),"",[tblPeopleClientsDayServices]![CityTown] & " - " & [tblPeopleClientsDayServices]![LocationName]) AS LocDay, IIf(IsNull([tblPeopleClientsVocationalServices]![CityTown]),"",[tblPeopleClientsVocationalServices]![CityTown] & " - " & [tblPeopleClientsVocationalServices]![Location]) AS LocVoc, Null AS Supervisor, tblPeople.IndexedName, tblPeople.LastName, tblPeople.FirstName, tblPeople.MiddleInitial, tblPeopleClientsDemographics.DateISP, tblPeopleClientsDemographics.DateConsentFormsSigned, tblPeopleClientsDemographics.DateBMMExpires, tblPeopleClientsDemographics.DateBMMAccessSignedHRC, tblPeopleClientsDemographics.DateBMMAccessSigned, tblPeopleClientsDemographics.DateSPDAuthExpires, tblPeopleClientsDemographics.DateSignaturesDueBy, tblPeopleClientsDemographics.AllSPDSignaturesReceived INTO temptbl0
FROM ((((tblPeople RIGHT JOIN tblPeopleClientsDemographics ON tblPeople.IndexedName = tblPeopleClientsDemographics.IndexedName) LEFT JOIN tblPeopleClientsCLOServices ON tblPeopleClientsDemographics.IndexedName = tblPeopleClientsCLOServices.IndexedName) LEFT JOIN tblPeopleClientsDayServices ON tblPeopleClientsDemographics.IndexedName = tblPeopleClientsDayServices.IndexedName) LEFT JOIN tblPeopleClientsResidentialServices ON tblPeopleClientsDemographics.IndexedName = tblPeopleClientsResidentialServices.IndexedName) LEFT JOIN tblPeopleClientsVocationalServices ON tblPeopleClientsDemographics.IndexedName = tblPeopleClientsVocationalServices.IndexedName
WHERE ((((tblPeopleClientsDemographics.ActiveDayServices)=True) AND ((tblPeopleClientsDayServices.Inactive)=False)) OR 
(((tblPeopleClientsDemographics.ActiveResidentialServices)=True) AND ((tblPeopleClientsResidentialServices.Inactive)=False)) OR 
(((tblPeopleClientsDemographics.ActiveCLO)=True) AND ((tblPeopleClientsCLOServices.Inactive)=False)) OR 
(((tblPeopleClientsDemographics.ActiveVocationalServices)=True) AND ((tblPeopleClientsVocationalServices.Inactive)=False))) AND 
tblPeople.IsDeceased = False;

