-- Query Name: qryEXPIRATIONS24
-- Extracted: 2026-01-29 16:09:05

INSERT INTO tblExpirations ( Location, RecordType, LastName, FirstName, Supervisor, JobTitle, AdjustedStartDate, LastVehicleChecklistCompleted, MostRecentAsleepFireDrill, NextRecentAsleepFireDrill, HouseSafetyPlanExpires, HousePlansReviewedByStaffBefore, DAYStaffTrainedInPrivacyBefore, DAYAllPlansReviewedByStaffBefore, DAYQtrlySafetyChecklistDueBy, MAPChecklistCompleted, HumanRightsOfficer, HROTrainsStaffBefore, HROTrainsIndividualsBefore, FireSafetyOfficer, FSOTrainsStaffBefore, FSOTrainsIndividualsBefore, DateISP, DateConsentFormsSigned, DateBMMExpires, DateBMMAccessSignedHRC, DateBMMAccessSigned, DateSPDAuthExpires, DateSignaturesDueBy, AllSPDSignaturesReceived, BBP, BackInjuryPrevention, CPR, DefensiveDriving, DriversLicense, FirstAid, MAPCert, PBS, SafetyCares, TB, WheelchairSafety, WorkplaceViolence, ProfessionalLicenses, ThreeMonthEvaluation, EvalDueBy, LastSupervision, OnLeave )
SELECT tblLocations.GPName, "Staff" AS RecordType, tblExpirations.LastName, tblExpirations.FirstName, tblPeople.GPSuperCode AS Supervisor, tblExpirations.JobTitle, tblExpirations.AdjustedStartDate, tblExpirations.LastVehicleChecklistCompleted, tblExpirations.MostRecentAsleepFireDrill, tblExpirations.NextRecentAsleepFireDrill, tblExpirations.HouseSafetyPlanExpires, tblExpirations.HousePlansReviewedByStaffBefore, tblExpirations.DAYStaffTrainedInPrivacyBefore, tblExpirations.DAYAllPlansReviewedByStaffBefore, tblExpirations.DAYQtrlySafetyChecklistDueBy, tblExpirations.MAPChecklistCompleted, tblExpirations.HumanRightsOfficer, tblExpirations.HROTrainsStaffBefore, tblExpirations.HROTrainsIndividualsBefore, tblExpirations.FireSafetyOfficer, tblExpirations.FSOTrainsStaffBefore, tblExpirations.FSOTrainsIndividualsBefore, tblExpirations.DateISP, tblExpirations.DateConsentFormsSigned, tblExpirations.DateBMMExpires, tblExpirations.DateBMMAccessSignedHRC, tblExpirations.DateBMMAccessSigned, tblExpirations.DateSPDAuthExpires, tblExpirations.DateSignaturesDueBy, tblExpirations.AllSPDSignaturesReceived, tblExpirations.BBP, tblExpirations.BackInjuryPrevention, tblExpirations.CPR, tblExpirations.DefensiveDriving, tblExpirations.DriversLicense, tblExpirations.FirstAid, tblExpirations.MAPCert, tblExpirations.PBS, tblExpirations.SafetyCares, tblExpirations.TB, tblExpirations.WheelchairSafety, tblExpirations.WorkplaceViolence, tblExpirations.ProfessionalLicenses, tblExpirations.ThreeMonthEvaluation, tblExpirations.EvalDueBy, tblExpirations.LastSupervision, tblExpirations.OnLeave
FROM (tblLocations INNER JOIN tblPeople ON tblLocations.StaffPrimaryContactIndexedName = tblPeople.IndexedName) INNER JOIN tblExpirations ON (tblPeople.LastName = tblExpirations.LastName) AND (tblPeople.FirstName = tblExpirations.FirstName)
WHERE (((tblLocations.GPName) Is Not Null) And ((tblPeople.GPSuperCode) Is Not Null) And ((tblLocations.Department)="Residential Services" Or (tblLocations.Department)="Day Services" Or (tblLocations.Department)="Vocational Services" Or (tblLocations.Department)="TILL NH" Or (tblLocations.Department)="Expirations Reporting") And ((Right(tblLocations!StaffPrimaryContactIndexedName,5))<>"TBD//")) Or (((tblLocations.GPName) Is Not Null) And ((tblPeople.GPSuperCode) Is Not Null) And ((tblLocations.CityTown)<>"Dedham") And ((tblLocations.Department)="Individualized Support Options") And ((Right(tblLocations!StaffPrimaryContactIndexedName,5))<>"TBD//"))
ORDER BY tblLocations.CityTown;

