' Module Name: Report_rptRESCLIENTSNoContacts
' Module Type: Document Module
' Lines of Code: 10
' Extracted: 2026-02-04 13:03:35

Option Compare Database
Option Explicit

Private Sub Report_Close()
On Error GoTo ShowMeError
    DoCmd.Close acForm, "frmRptRESCLIENTS"
    Exit Sub
ShowMeError:
    MsgBox "Error # " & Str(Err.Number) & " was generated by " & Me.Name & Chr(13) & Err.Description, vbOKOnly, "Error", Err.HelpFile, Err.HelpContext
End Sub
