' Module Name: Report_rptCONSUMMARY
' Module Type: Document Module
' Lines of Code: 14
' Extracted: 1/29/2026 4:12:24 PM

Option Compare Database
Option Explicit

Private Sub Report_Close()
On Error GoTo ShowMeError
    DoCmd.Close acForm, "frmRptCONSUMMARY"
    Exit Sub
ShowMeError:
    MsgBox "Error # " & Str(Err.Number) & " was generated by " & Me.Name & Chr(13) & Err.Description, vbOKOnly, "Error", Err.HelpFile, Err.HelpContext
End Sub

Private Sub Report_Load()
    FY = Me.OpenArgs
End Sub